// apps/svelte-example/src/App.svelte
<script lang="ts">
  import { trigger } from 'web-haptics';
</script>

<div class="container">
  <button on:click={() => trigger()}>Tap me</button>
</div>

<style>
  .container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    font-size: 2rem;
  }
</style>

// apps/vue-example/src/App.vue
<template>
  <div class="container">
    <button @click="trigger()">Tap me</button>
  </div>
</template>

<script setup lang="ts">
import { trigger } from "web-haptics";
</script>

<style>
.container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  font-size: 2rem;
}
</style>
