// apps/react-example/src/App.tsx
import { trigger } from "web-haptics";

export default function App() {
  return (
    <div
      style={{
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        height: "100vh",
        fontSize: "2rem",
      }}
    >
      <button onClick={() => trigger()}>Tap me</button>
    </div>
  );
}

// apps/svelte-example/src/App.svelte
<script lang="ts">
  import { trigger } from 'web-haptics';
</script>

<div class="container">
  <button on:click={() => trigger()}>Tap me</button>
</div>

<style>
  .container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    font-size: 2rem;
  }
</style>
